In [1]:
print("a")

a


# NEDEN NUMPY ?

## BU BİR ALTBAŞLIKTIR.

In [6]:
a = [1,2,3,4]
b = [2,3,4,5]     
a
b

[2, 3, 4, 5]

a = [1,2,3,4]
b = [2,3,4,5]     
a
b


üstteki gibi a b tanımladıktan sonra a b yazıp çağırırsak sadece en alttakini getirecektir.

In [7]:
a

[1, 2, 3, 4]

In [8]:
ab =[]

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

[2, 6, 12, 20]

In [9]:
import numpy as np

In [10]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [11]:
a*b

array([ 2,  6, 12, 20])

# NUMPY ARRAY'I OLUŞTURMAK

In [12]:
import numpy as np

In [13]:
a = np.array([1,2,3,4])

In [14]:
type(a)

numpy.ndarray

In [16]:
np.array([3.14,4,2,13])

array([ 3.14,  4.  ,  2.  , 13.  ])

tüm sayıları ondalığa çevirdi sabit tip vardır numpy arrayde.

In [17]:
np.array([3.14,4,2,13], dtype = "int")

array([ 3,  4,  2, 13])

# sıfırdan array oluşturma

In [27]:
np.zeros(10,dtype = int) #tek boyutlu array 0 lardan oluşan

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [26]:
np.ones((3,5),dtype = int) #iki boyutlu array 1 lerden oluşan

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [28]:
np.full((3,5),3) #3 lerden oluşan 3x5 lik dizi

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [29]:
np.arange(0,31,3)  #0 dan 31 e kadar üçer üçer artacak şekilde dizi oluşturu.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [30]:
np.linspace(0,1,10) #0 ile 1 arasında 10 tane sayı oluştur.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [31]:
np.random.normal(10,4,(3,4)) # ort:10 sp:4 3x4 lük array oluştur

array([[ 2.28545287,  6.89331096,  9.96509313,  8.1233958 ],
       [ 4.86052487,  8.84601917, 12.8784824 , 13.13320759],
       [12.04272516, -0.83348157,  0.85251653, 12.46818181]])

In [34]:
np.random.randint(0,10,(3,3)) # 0-10 arası int değerlerden rastgele array

array([[5, 3, 1],
       [1, 6, 4],
       [3, 5, 9]])

* **ndim:** _boyut sayısı_
* shape: boyut bilgisi
* size: toplam eleman sayısı
* dtype: array veri tipi

In [35]:
import numpy as np

In [ ]:
np.random.randint(10,size=10) #0-10 arası rastgele 10 tane int değerler oluşturdu.

In [38]:
a = np.random.randint(10,size=10) # kayıt ettik.

In [39]:
a.ndim #boyut bilgisini verdi 1

1

In [41]:
a.shape   #tek boyutlu old. için tek boyut bilgisi veriliyor.

(10,)

In [43]:
a.dtype   #içerisinin int tipini vermiş oldu.

dtype('int32')

In [48]:
b = np.random.randint(10,size =(3,5)) #3x5 lik array 0-10 arası sayılar

In [47]:
b

array([[1, 8, 5, 7, 2],
       [6, 2, 6, 7, 5],
       [1, 0, 6, 5, 5]])

In [49]:
b.ndim

2

In [50]:
b.shape

(3, 5)

In [51]:
b.dtype

dtype('int32')

In [52]:
b.size

15

## YENİDEN ŞEKİLLENDİRME (RESHAPİNG)

In [54]:
import numpy as np

In [55]:
np.arange(1,10) #1-10 dan oluşan array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.arange(1,10).reshape((3,3))  #3x3 lük bir matrise çevirebilirim

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
a = np.arange(1,10)

In [59]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.ndim    #tek boyutlu array = vektör,iki boyutlu array=matris

1

In [67]:
b = a.reshape((1,9))  #bu çıktıda farklı olarak iki köşeli parantez bulunur.
#iki boyutlu matris oldu bir satır 9 sütunlu

In [68]:
b.ndim

2

## ARRAY BİRLEŞTİRME (CONCATENATİON)

In [69]:
import numpy as np 

In [70]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [72]:
np.concatenate([x,y])   # iki arrayı birleştirdi.

array([1, 2, 3, 4, 5, 6])

In [73]:
z = np.array([7,8,9])

In [75]:
np.concatenate([x,y,z])  # 3 tane numpy arrayı birleştirdik.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

## İKİ BOYUT

In [77]:
a = np.array([[1,2,3],
            [4,5,6]])

In [79]:
np.concatenate([a,a])  #iki boyutlu birleştirme

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [80]:
np.concatenate([a,a],axis = 0) # 0 isesatır bazında, 1 ise sütun bazında birleştirir,yan yana

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [81]:
np.concatenate([a,a],axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

## ARRAY AYIRMA (SPLİTTİNG)

import numpy as np

In [87]:
x = np.array([1,2,3,99,99,3,2,1])  # 3 ve 5 den ayır.
#2 indeks verdiğimiz için 3 ayırıyor,3 verseydik 4 ayırırdı.

In [86]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [88]:
a,b,c = np.split(x,[3,5])

In [89]:
a

array([1, 2, 3])

In [90]:
b

array([99, 99])

In [91]:
c

array([3, 2, 1])

####  İKİ BOYULTU AYIRMA

In [92]:
m = np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [93]:
np.vsplit(m,[2]) # indeks 2 ye kadar böl.

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [94]:
ust, alt = np.vsplit(m,[2])

In [95]:
ust

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [96]:
alt

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [97]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [103]:
np.hsplit(m,[2])

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [102]:
sag,sol =np.hsplit(m,[2])  # dikey böldü.

In [100]:
sag

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [101]:
sol

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

## SIRALAMA (SORTING)

In [104]:
import numpy as np

In [105]:
v = np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [110]:
np.sort(v)     #numpy içinden sort çağrıldığında orjinal yapıyı bomzadı.

array([1, 2, 3, 4, 5])

In [107]:
v

array([2, 1, 4, 3, 5])

In [111]:
v.sort()    #burda çağırdığımızda v nin orjinal yapısını bozdu,değiştirdi.

In [109]:
v

array([1, 2, 3, 4, 5])

### İKİ BOYUTLU ARRAY SIRALAMA

In [116]:
m = np.random.normal(20,5,(3,3)) #ort:20 sp:5 3x3 lük
m

array([[ 8.06754851, 20.9767865 , 10.92168499],
       [24.10466296, 20.51128942, 30.57775055],
       [20.91838829, 13.2043244 , 28.1960092 ]])

In [118]:
np.sort(m,axis =1)   #her bir satırı kendi içinde küçükten büyüğe olacak şekilde sıralamış.

array([[ 8.06754851, 10.92168499, 20.9767865 ],
       [20.51128942, 24.10466296, 30.57775055],
       [13.2043244 , 20.91838829, 28.1960092 ]])

In [120]:
np.sort(m,axis =0) #her bir sütunu kendi içinde küçükten büyüğe olacak şekilde sıralamış.

array([[ 8.06754851, 13.2043244 , 10.92168499],
       [20.91838829, 20.51128942, 28.1960092 ],
       [24.10466296, 20.9767865 , 30.57775055]])

### İNDEX İLE ELEMANLARA ERİŞMEK

In [121]:
import numpy as np

In [122]:
a = np.random.randint(10,size = 10)
a

array([7, 4, 3, 8, 6, 0, 4, 6, 4, 8])

In [123]:
a[0]

7

In [125]:
a[-1] #tersten erişim sondaki eleman

8

In [128]:
a[0]=100  # elemanı indeksle değiştriebilirz.

In [127]:
a

array([100,   4,   3,   8,   6,   0,   4,   6,   4,   8])

In [130]:
m = np.random.randint(10,size = (3,5))
m

array([[7, 3, 4, 5, 8],
       [6, 9, 0, 3, 8],
       [3, 1, 7, 7, 0]])

In [132]:
m[0,0] #indeksler 0 dan başlıyor.

7

In [135]:
m[1,1]=2.2  # 2 koyar tek tiptir numpy array
m

array([[7, 3, 4, 5, 8],
       [6, 2, 0, 3, 8],
       [3, 1, 7, 7, 0]])

### SLİCİNG İLE ELEMANLARA ERİŞMEK (ARRAY ALT KÜMESİNE ERİŞMEK)

In [136]:
import numpy as np

In [138]:
a = np.arange(20,30)
a

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [140]:
a[0:3]    # 0 dan başla 3 tane göster

array([20, 21, 22])

In [141]:
a[:3]    # 0 dan başla 3 tane göster

array([20, 21, 22])

In [143]:
a[3:]   # 3 den sona doğru 3 dahil tüm değerleri seç

array([23, 24, 25, 26, 27, 28, 29])

In [145]:
a[1::2]  #1 den başla 2 atlayarak göster

array([21, 23, 25, 27, 29])

### iki boyutlu slice işlemleri

In [146]:
m = np.random.randint(10,size = (5,5))
m 

array([[8, 7, 2, 4, 5],
       [6, 3, 1, 4, 0],
       [0, 5, 6, 6, 2],
       [5, 5, 0, 8, 5],
       [8, 1, 6, 5, 6]])

In [148]:
m[:,0] # 0 sütunu getir,tüm satırlarıyla

array([8, 6, 0, 5, 8])

In [149]:
m[:,1]   # 2.sütuna eriştik

array([7, 3, 5, 5, 1])

In [155]:
m

array([[8, 7, 2, 4, 5],
       [6, 3, 1, 4, 0],
       [0, 5, 6, 6, 2],
       [5, 5, 0, 8, 5],
       [8, 1, 6, 5, 6]])

In [153]:
m[0,:]      #1 satırın tüm sütunları m[satır,sütun]

array([8, 7, 2, 4, 5])

In [156]:
m[0:2, 0:3] # 0 dan 2 ye kadar satırlar, 0 dan 3 e kadar sütunlar gelir.

array([[8, 7, 2],
       [6, 3, 1]])

In [158]:
m[::,:2]    # = m[:,:2] 

array([[8, 7],
       [6, 3],
       [0, 5],
       [5, 5],
       [8, 1]])

In [159]:
m

array([[8, 7, 2, 4, 5],
       [6, 3, 1, 4, 0],
       [0, 5, 6, 6, 2],
       [5, 5, 0, 8, 5],
       [8, 1, 6, 5, 6]])

In [160]:
m[1:3, 0:2]

array([[6, 3],
       [0, 5]])

### ALT KÜME ÜZERİNDE İŞLEM YAPMAK 

In [161]:
import numpy as np 

In [162]:
a = np.random.randint(10,size =(5,5))
a

array([[3, 2, 8, 4, 0],
       [4, 1, 6, 0, 3],
       [9, 0, 4, 3, 2],
       [4, 6, 1, 1, 2],
       [6, 3, 3, 1, 9]])

In [163]:
alt_a = a[0:3,0:2]
alt_a

array([[3, 2],
       [4, 1],
       [9, 0]])

In [164]:
alt_a[0,0] = 9999
alt_a[1,1] = 888

In [165]:
alt_a

array([[9999,    2],
       [   4,  888],
       [   9,    0]])

In [166]:
a

array([[9999,    2,    8,    4,    0],
       [   4,  888,    6,    0,    3],
       [   9,    0,    4,    3,    2],
       [   4,    6,    1,    1,    2],
       [   6,    3,    3,    1,    9]])

In [167]:
m = np.random.randint(10,size =(5,5))
m

array([[4, 1, 5, 2, 3],
       [6, 9, 8, 9, 5],
       [6, 3, 6, 6, 3],
       [2, 0, 3, 1, 5],
       [3, 7, 6, 8, 2]])

In [172]:
alt_b = m[0:3,0:2].copy()   #copy ekleyerek sadecealtkümeye ekleriz ana arraye m de değişiklik olmaz.
alt_b

array([[4, 1],
       [6, 9],
       [6, 3]])

In [173]:
alt_b[0,0] = 9999 
alt_b

array([[9999,    1],
       [   6,    9],
       [   6,    3]])

In [174]:
m

array([[4, 1, 5, 2, 3],
       [6, 9, 8, 9, 5],
       [6, 3, 6, 6, 3],
       [2, 0, 3, 1, 5],
       [3, 7, 6, 8, 2]])

### FANCY INDEX İLE ELEMANLARA ERİŞMEK 

In [175]:
import numpy as np

In [176]:
v = np.arange(0,30,3)
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [177]:
v[1]

3

In [181]:
v[3]

9

In [182]:
v[5]

15

In [184]:
[v[1],v[3],v[5]]      # bi kaç tane erişmek için bu şekilde liste şeklinde de erişilebilir.

[3, 9, 15]

In [187]:
al_getir = [1,3,5]
v

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [190]:
v[al_getir] # v nin 1,3,5 indekslerini getirir.bu işleme fancy indeks deriz.

array([ 3,  9, 15])

### iki boyutta fancy

In [191]:
m = np.arange(9).reshape((3,3))
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [194]:
satir = np.array([0,1])  #1
sutun = np.array([1,2])  #5

In [195]:
m[satir,sutun]

array([1, 5])

### basit index ile fancy index

In [196]:
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [198]:
m[0,[1,2]]       #fancy ile basit indexlemeyi bir arada kullandım.

array([1, 2])

# slice ile fancy

In [199]:
m[0:,[1,2]] # 0 dan sona kadar gitti

array([[1, 2],
       [4, 5],
       [7, 8]])

### KOŞULLU ELEMAN İŞLEMLERİ

In [200]:
import numpy as np

In [201]:
v= np.array([1,2,3,4,5])

In [203]:
v < 3    #küçük olanları true false ile gördük

array([ True,  True, False, False, False])

In [205]:
v[v<3]    # true değerleri geldi

array([1, 2])

In [206]:
v[v>3]

array([4, 5])

In [207]:
v[v<=3]

array([1, 2, 3])

In [208]:
v[v>=3]

array([3, 4, 5])

In [209]:
v[v==3]

array([3])

In [210]:
v[v!=3]

array([1, 2, 4, 5])

In [211]:
v*2

array([ 2,  4,  6,  8, 10])

In [212]:
v/5

array([0.2, 0.4, 0.6, 0.8, 1. ])

In [213]:
v*5/10

array([0.5, 1. , 1.5, 2. , 2.5])

In [214]:
v**2

array([ 1,  4,  9, 16, 25])

### matematiksel işlemler

In [215]:
import numpy as np

In [216]:
v = np.array([1,2,3,4,5])
v

array([1, 2, 3, 4, 5])

### matematiksel işlemleri yaparken ufunc adı verilen mekanizma çalışıyor.

In [219]:
np.subtract(v,1)

array([0, 1, 2, 3, 4])

In [220]:
np.add(v,1)

array([2, 3, 4, 5, 6])

In [221]:
np.multiply(v,4)

array([ 4,  8, 12, 16, 20])

In [222]:
np.divide(v,3)

array([0.33333333, 0.66666667, 1.        , 1.33333333, 1.66666667])

In [224]:
np.power(v,3)  #küp alır üçünkü kuvveti

array([  1,   8,  27,  64, 125], dtype=int32)

In [226]:
np.mod(v,2)  # 2 ye bölümünden kalanları getirir.

array([1, 0, 1, 0, 1], dtype=int32)

In [228]:
np.absolute(np.array([-3]))   #mutlak değer almak için kullanılıyor.

array([3])

In [230]:
np.sin(360)
np.cos(180)

-0.5984600690578581

In [231]:
v = np.array([1,2,3])

In [232]:
np.log(v)

array([0.        , 0.69314718, 1.09861229])

In [233]:
np.log2(v)

array([0.       , 1.       , 1.5849625])

In [234]:
np.log10(v)

array([0.        , 0.30103   , 0.47712125])

### ?np şeklinde dökümantasyona ulaşılabilir.

### cheatsheet kütüphanein içeriği kopya kağıdı şeklinde

# istatistiksel hesaplamalar 

In [242]:
v

array([1, 2, 3])

In [239]:
np.mean(v)  # ortalaa verir.

2.0

In [240]:
v.sum()

6

In [241]:
v.min()

1

In [243]:
v.max()

3

# NUMPY ile iki bilinmeyenli denklem çözümü

In [245]:
import numpy as np

In [249]:
#   5*x0+x1 = 12
#   x0+3*x1 = 10

In [250]:
a = np.array([[5,1],[1,3]])
b = np.array([12,10])


In [251]:
a

array([[5, 1],
       [1, 3]])

In [252]:
b

array([12, 10])

In [254]:
x = np.linalg.solve(a,b)  #iki argümanın arasındaki ilişkiye göre cevabı bul diyoruz.
x

array([1.85714286, 2.71428571])